project_id = "tkwwpcgmpemkrsubilhi"

[functions.validate-setup]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.meta-webhook]
verify_jwt = false

[functions.test-meta-webhook]
verify_jwt = false

[functions.db-backup-sync]
verify_jwt = false